var mythandFolklore = [
  "Apprentice",
  "Assistant",
  "Forester",
  "Holy_Knight",
  "Inquisitor",
  "Knight_Errant",
  "Monk",
  "Naturalist",
  "Outcast",
  "Philosopher",
  "Protector",
  "Researcher",
  "Scholar",
  "Spanish_Agent",
  "Vicar",
  "Vigilante",
  "Woodswoman",
];
var seaofSand = [
  "Alchemist",
  "Chaplain",
  "Citizen",
  "Confidante",
  "Countess",
  "Follower",
  "Freedman",
  "Fugitive",
  "Hospitaller",
  "Knight",
  "Marabout",
  "Matron",
  "Occultist",
  "Pirate",
  "Sailor",
  "Soothsayer",
  "Squire",
  "Townswoman",
];
var witchwood = [
  "The_Brave",
  "The_Bride",
  "The_Broken",
  "The_Companion",
  "The_Crone",
  "The_Drowner",
  "The_Fair",
  "The_Fearless",
  "The_Fighter",
  "The_Forlorn",
  "The_Hag",
  "The_Maiden",
  "The_Matriarch",
  "The_Mother",
  "The_Noonmaiden",
  "The_Noonwraith",
  "The_Prince",
  "The_Revenant",
  "The_Rusalka",
  "The_Traveler",
  "The_Vampire",
  "The_Vestal",
  "The_Wanderer",
  "The_Warrior",
];
var destinies = [
  "Afflictor",
  "Corruptor",
  "Defender",
  "Guardian",
  "Henchman",
  "Herbalist",
  "Huntsman",
  "Mercenary",
  "Noble",
  "Nun",
  "Pilgram",
  "Savior",
  "Sentinel",
  "Servant",
  "Shepherd",
  "Soldier",
  "The_Coward",
  "The_Cruel",
  "The_Disgraced",
  "The_Faithless",
  "The_Highborn",
  "The_Humble",
  "The_Meek",
  "The_Profane",
  "The_Righteous",
  "The_Sage",
  "The_Wicked",
  "The_Wise",
  "Trapper",
  "Witch",
  "Woodsman",
];
var glitters = [
  "The_Accountant",
  "The_Acolyte",
  "The_Mayor",
  "The_Miner",
  "The_Mystic",
  "The_Son",
];

var items = [
  "01-Horse",
  "02-Bloody Trophy",
  "03-Shield",
  "04-Bow",
  "05-Hatchet",
  "06-Talisman",
  "07-Food",
  "08-Rosary",
  "09-Holy Water",
  "10-Lockpick",
  "101-Scalemail",
  "102-Camel",
  "103-Boat",
  "104-Scimitar",
  "105-Gunpowder Keg",
  "106-Hamsa",
  "107-Assassins Dagger",
  "108-Carpet",
  "109-Lamp",
  "11-Herbs",
  "110-Drawing",
  "111-Oriflamme",
  "112-Figure of Asclepius",
  "113-Figure of Mars",
  "114-Figure of Mercury",
  "115-Figure of Neptune",
  "116-Figure of Pluto",
  "117-Figure of Venus",
  "118-Figure of Vulcan",
  "119-Map",
  "12-Medicine",
  "120-Clay Tablet",
  "121-Cogwheel",
  "122-Stone Scarb",
  "123-Stone Cat",
  "124-Stone Owl",
  "125-Lion",
  "126-Roc",
  "127-Giant Scorpion",
  "128-Crown Jewels",
  "129-Astrolabe",
  "13-Alcohol",
  "130-Tifnagh Ring",
  "131-Wooden Chest",
  "132-Casket",
  "14-Sword",
  "15-Torch",
  "16-Trap",
  "17-Rope",
  "18-Poison",
  "19-Legal Document",
  "20-Spade",
  "201-Leeches",
  "202-Fishsing Rod",
  "203-Pike",
  "204-Anchor",
  "205-Jesters Hat",
  "206-Templar Sword",
  "207-Crystal of Echoes",
  "208-Nightingale",
  "209-Oars",
  "21-Doctors Mask",
  "210-Flying Fish",
  "211-Lionfish",
  "212-Willow Seeds",
  "213-Straw Doll",
  "214-Cat",
  "215-Counting Board",
  "216-Magnifying Glass",
  "217-Hourglass",
  "218-Quill and Ink",
  "219-Tongs",
  "22-Votive Candle",
  "220-Hand of Saint",
  "221-Ear of Saint",
  "222-Finger of Saint",
  "223-Eye of Saint",
  "224-Bible",
  "225-Cherubs Head",
  "226-Granite Wing",
  "227-Halo of Dawn",
  "228-Halo of Dusk",
  "229-Trumpet of Dawn",
  "23-Dice",
  "230-Trumpet of Dusk",
  "231-Boar",
  "232-Tainted Skull",
  "233-Vile Blood",
  "234-Darkhammer",
  "235-Lughs Tounge",
  "236-Black Chain",
  "237-Cult Ring",
  "24-Parchments",
  "25-Silver Dagger",
  "26-Dog",
  "27-Crossbow",
  "28-Will-o-Wisp",
  "29-Wolf Den Trophy",
  "30-Crucifix",
  "301-Red Ribbon",
  "302-Mead",
  "303-Breadcrumbs",
  "304-Charred Feather",
  "305-Golden Apple",
  "306-Hagstone",
  "307-Sunflowers",
  "308-Summer Wreath",
  "309-Nightshade",
  "31-Flute",
  "310-Confusing Map",
  "311-Puzzling Map",
  "312-Baffling Map",
  "313-Perplexing Map",
  "314-Mark of the Sun",
  "315-Mark of the Thunder",
  "316-Mark of the Moon",
  "317-Bronze Sword",
  "318-Broom",
  "319-Flint Arrows",
  "32-Ornamented Key",
  "320-Golden Knife",
  "321-Cauldron",
  "322-Toad",
  "323-Rooster",
  "324-Serpent",
  "325-Savage Soul",
  "326-Binding Chain",
  "327-Iron Tooth",
  "328-Evil Eye",
  "329-Shard of Will",
  "33-Chalice",
  "330-Enchanted Mortar",
  "331-Drum",
  "332-Fireflies",
  "34-Lantern",
  "35-Innocent Blood",
  "36-Corrupted Paw",
  "37-Obsidian Knife",
  "38-Occult Folio",
  "39-Horned Mask",
  "40-Hand Mirror",
  "41-Silver Spear",
  "42-Censer",
  "43-Stallion",
  "44-Signet Ring",
  "45-Sheep",
  "46-Chainmail",
  "47-Toolbox",
  "48-Devils Horn",
  "49-Divine Sword",
  "50-Lyre",
  "51-Harvest Wreath",
  "52-Copper Sickle",
  "53-Stone Idol",
  "54-Magic Flower",
  "55-Flail",
  "56-Garotte",
  "57-Tarot Card-Popess",
  "58-Tarot Card-Fool",
  "59-Tarot Card-Death",
  "60-Tarot Card-World",
  "61-Tarot Card-Judgement",
  "62-Tarot Card-Moon",
  "63-Ladder",
  "64-Ashes of Saint",
  "65-Crosier",
  "66-Crow",
  "67-Bell",
  "68-Salt",
  "69-Sacred Banner",
  "70-Heart of Saint",
  "71-Skull of Saint",
  "72-Net",
  "73-Heart of the Swarm",
  "74-Reapers Blade",
  "75-Blessed Soul",
  "76-Cursed Soul",
];
